name = "SymbolicIndexingInterface"
uuid = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
authors = ["Aayush Sabharwal <aayush.sabharwal@gmail.com> and contributors"]
version = "0.3.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[extensions]
SymbolicIndexingInterfaceSymbolicUtilsExt = "SymbolicUtils"
SymbolicIndexingInterfaceSymbolicsExt = "Symbolics"

[compat]
Requires = "1.0"
SymbolicUtils = "1.4"
Symbolics = "5.10"
julia = "1"

[extras]
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SymbolicUtils", "Symbolics","Test"]
