name: "Tests"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  tests:
    name: "Tests"
    strategy:
      matrix:
        group:
          - "Core"
          - "Downstream"
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      group: "${{ matrix.group }}"
    secrets: "inherit"
